source_urls = [
    'http://ir.eia.gov/wpsr/psw01.xls',
    'http://ir.eia.gov/wpsr/psw02.xls',
    'http://www.eia.gov/dnav/pet/hist_xls/W_EPC0_SAX_YCUOK_MBBLw.xls',
    'http://www.eia.gov/dnav/pet/xls/PET_SUM_SNDW_DCUS_NUS_W.xls'
]

data_directory = './data'


# default yaxis_name is "Millions".  If key is missing chart will render with y axis name of "Millions"
charts = [
    {
        'name': 'Chart1',
        'title': 'Commercial Crude Oil Stocks<br />(Millions of Barrels)<br />Week Ending ',
        'data_file': 'psw01.xls',
        'data_sheet': 'Data 1',
        'data_id': 'WCESTUS1',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart2',
        'title': 'Commercial Crude Oil Stocks, Cushing OK<br />(Millions of Barrels)<br />Week Ending ',
        'data_file': 'W_EPC0_SAX_YCUOK_MBBLw.xls',
        'data_sheet': 'Data 1',
        'data_id': 'W_EPC0_SAX_YCUOK_MBBL',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart3',
        'title': 'Commercial Crude Oil Imports<br />(Millions of Barrels per Day)<br />Week Ending ',
        'data_file': 'psw01.xls',
        'data_sheet': 'Data 2',
        'data_id': 'WCEIMUS2',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart4',
        'title': 'Refiner Net Input of Crude Oil<br />(Millions of Barrels per Day)<br />Week Ending ',
        'data_file': 'psw01.xls',
        'data_sheet': 'Data 2',
        'data_id': 'WCRRIUS2',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart5',
        'title': 'Motor Gasoline Stocks<br />(Millions of Barrels)<br />Week Ending ',
        'data_file': 'psw01.xls',
        'data_sheet': 'Data 1',
        'data_id': 'WGTSTUS1',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart6',
        'title': 'Distillate Fuel Oil Stocks<br />(Millions of Barrels)<br />Week Ending ',
        'data_file': 'psw01.xls',
        'data_sheet': 'Data 1',
        'data_id': 'WDISTUS1',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart7',
        'title': 'Propane Stocks<br />(Millions of Barrels)<br />Week Ending ',
        'data_file': 'psw01.xls',
        'data_sheet': 'Data 1',
        'data_id': 'WPRSTUS1',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart8',
        'title': 'Total Crude Oil and Petroleum Products Stocks (Excluding SPR)<br />(Millions of Barrels)<br />Week Ending ',
        'data_file': 'psw01.xls',
        'data_sheet': 'Data 1',
        'data_id': 'WTESTUS1',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart9',
        'title': 'Motor Gasoline Products Supplied<br />(Millions of Barrels per Day)<br />Week Ending ',
        'data_file': 'psw01.xls',
        'data_sheet': 'Data 2',
        'data_id': 'WGFUPUS2',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart10',
        'title': 'Distillate Fuel Oil Products Supplied<br />(Millions of Barrels per Day)<br />Week Ending ',
        'data_file': 'psw01.xls',
        'data_sheet': 'Data 2',
        'data_id': 'WDIUPUS2',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart11',
        'title': 'Propane Products Supplied<br />(Millions of Barrels per Day)<br />Week Ending ',
        'data_file': 'psw01.xls',
        'data_sheet': 'Data 2',
        'data_id': 'WPRUP_NUS_2',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 0.001,
        'auto_open': False,
    },
    {
        'name': 'Chart12',
        'title': 'U.S. Refinery Utilization<br />(Percentage of Operable Capacity)<br />Week Ending ',
        'data_file': 'psw02.xls',
        'data_sheet': 'Data 1',
        'data_id': 'WPULEUS3',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 1,
        'auto_open': False,
        'yaxis_name': 'Percent',
    },
    {
        'name': 'Chart13',
        'title': 'Commercial Crude Oil Days of Supply<br />(Millions of Barrels)<br />Week Ending ',
        'data_file': 'PET_SUM_SNDW_DCUS_NUS_W.xls',
        'data_sheet': 'Data 7',
        'data_id': 'W_EPC0_VSD_NUS_DAYS',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 1,
        'auto_open': False,
        'yaxis_name': 'Number of Days',
    },
    {
        'name': 'Chart14',
        'title': 'Motor Gasoline Days of Supply<br />(Millions of Barrels)<br />Week Ending ',
        'data_file': 'PET_SUM_SNDW_DCUS_NUS_W.xls',
        'data_sheet': 'Data 7',
        'data_id': 'W_EPM0_VSD_NUS_DAYS',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 1,
        'auto_open': False,
        'yaxis_name': 'Number of Days',
    },
    {
        'name': 'Chart15',
        'title': 'Distillate Fuel Oil Days of Supply<br />(Millions of Barrels)<br />Week Ending ',
        'data_file': 'PET_SUM_SNDW_DCUS_NUS_W.xls',
        'data_sheet': 'Data 7',
        'data_id': 'W_EPD0_VSD_NUS_DAYS',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 1,
        'auto_open': False,
        'yaxis_name': 'Number of Days',
    },
    {
        'name': 'Chart16',
        'title': 'Propane Days of Supply<br />(Millions of Barrels)<br />Week Ending ',
        'data_file': 'PET_SUM_SNDW_DCUS_NUS_W.xls',
        'data_sheet': 'Data 7',
        'data_id': 'W_EPLLPZ_VSD_NUS_DAYS',
        'chart_type': 'MultiYearWeeklyDataTrendChart',
        'num_years': 5,
        'timeframe_unit': 'Year',
        'data_scale_factor': 1,
        'auto_open': False,
        'yaxis_name': 'Number of Days',
    },
]